Forum/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class ForumController : Controller
    {
        // GET: Forum
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Posts()
        {
            return View();
        }

        public ActionResult NewPost()
        {
            return View();
        }
    }
}

Forum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Blog()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Aşağıdaki iletişim bilgileri ile bize ulaşabilirsiniz.";

            return View();
        }
    }
}

Forum/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Id()
        {
            return View();
        }
    }
}

Forum/Views/Home/About.cshtml
@{
    ViewBag.Title = "Hakkında";
}
<h2 class="page-h">@ViewBag.Title</h2>

<p>Toplumu ilgilendiren bir konu hakkında farklı fikirlere sahip dinleyici gruplarının oluşturduğu tartışma ortamına forum denir. Bir başkan tarafından yönetilir. Panelle benzerlik gösterir. Tek fark forumda seyirciler de görüş bildirebilmektedir.
</p>

Forum/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "İletişim";
}
<h2 class="page-h">@ViewBag.Title</h2>
<h3 class="page-h3">@ViewBag.Message</h3>

<address>
    Sakarya Üniversitesi<br />
    Serdivan, Esentepe Kampüsü<br />
    <abbr title="Phone">Tel:</abbr>
    050000300320
</address>

<address>
    <strong>Destek:</strong>   <a href="mailto:destek@codeforum.com">destek@codeforum.com</a><br />
    <strong>Sponsor:</strong> <a href="mailto:sponsor@example.com">sponsor@codeforum.com</a>
</address>

Forum/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="panel panel-default" style="margin-top:10px;">
    <div class="panel-heading">Proje Sahibi (Öğrenci)</div>
    <div class="panel-body"><b>Ad Soyad :</b> Gürbüz Uğurgül<br /><b>Öğrenci Numarası :</b> b151210025</div>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Kategori</th>
            <th>Konu Başlığı</th>
            <th class="ct-user-h">Yazar</th>
            <th class="ct-msg-h">Mesajlar</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="ct-img"><img src="/Content/Images/python.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">Python for döngüsü Kullanımı</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">admin</a></td>
            <td class="ct-msg">2</td>
        </tr>
        <tr>
            <td class="ct-img"><img src="/Content/Images/js.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">JavaScript Oyun Geliştirme Üzerine</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">gurbuz</a></td>
            <td class="ct-msg">3</td>
        </tr>
        <tr>
            <td class="ct-img"><img src="/Content/Images/js.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">JavaScript Çerez Kullanımı</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">arda</a></td>
            <td class="ct-msg">12</td>
        </tr>
        <tr>
            <td class="ct-img"><img src="/Content/Images/java.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">Python for döngüsü Kullanımı</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">admin</a></td>
            <td class="ct-msg">2</td>
        </tr>
        <tr>
            <td class="ct-img"><img src="/Content/Images/php.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">Üyelik Sistemi Oluşturma (Giriş ve Kayıt)</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">gurbuz</a></td>
            <td class="ct-msg">3</td>
        </tr>
        <tr>
            <td class="ct-img"><img src="/Content/Images/python.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">Yüksek Basamaklı Sayıların Hesaplanması</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">arda</a></td>
            <td class="ct-msg">12</td>
        </tr>
        <tr>
            <td class="ct-img"><img src="/Content/Images/java.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">Java Programlamaya Giriş</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">cihan</a></td>
            <td class="ct-msg">2</td>
        </tr>
        <tr>
            <td class="ct-img"><img src="/Content/Images/php.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">PHP Nasıl Öğrenilir? Nasıl Çalışmalıyım?</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">gurbuz</a></td>
            <td class="ct-msg">3</td>
        </tr>
        <tr>
            <td class="ct-img"><img src="/Content/Images/js.png" /></td>
            <td class="ct-konu"><a href="@Url.Action("Posts", "Forum")">JavaScript ile Yapılabilecekler</a><p class="ct-konu-ek">Tarih : 26 Kasım 2016</p></td>
            <td class="ct-user"><a href="@Url.Action("Id", "User")">ali</a></td>
            <td class="ct-msg">12</td>
        </tr>
    </tbody>
</table>